name: Update Railpack Version List

on:
  workflow_dispatch:

jobs:
  update-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write # リポジトリへの書き込み権限を明示

    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v4

      - name: Goのセットアップ
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: リストの更新
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go run fetch_and_generate.go

      - name: 変更をコミットとプッシュ
        shell: bash
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # ワークフロー以外のファイルを追加
          git add railpack_releases.json
          # 差分がある場合のみコミットしてプッシュ
          git status
          git diff --staged --exit-code || (git commit -m "chore: update railpack version list" && git push)
